export const actionTypes = {
  GET_ARTICLE_BY_ID: "GET_ARTICLE_BY_ID",
  GET_ALL_ARTICLES: "GET_ALL_ARTICLES",
  CREATE_NEW_COLLECT: "CREATE_NEW_COLLECT",
  GET_ALL_COLLECTS: "GET_ALL_COLLECTS",
  CREATE_NEW_ARTICLE: "CREATE_NEW_ARTICLE",
  UPDATE_ARTICLE: "UPDATE_ARTICLE",
  LOGIN: "LOGIN",
  LOGGED: "LOGGED"
};
