export const actionTypes = {
  FAILURE: "FAILURE",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",
  LOAD_DATA: "LOAD_DATA",
  LOAD_DATA_SUCCESS: "LOAD_DATA_SUCCESS",
  START_CLOCK: "START_CLOCK",
  TICK_CLOCK: "TICK_CLOCK",
  GET_ARTICLE_BY_ID: "GET_ARTICLE_BY_ID",
  GET_ALL_ARTICLES: "GET_ALL_ARTICLES",
  CREATE_NEW_COLLECT: "CREATE_NEW_COLLECT",
  GET_ALL_COLLECTS: "GET_ALL_COLLECTS",
  CREATE_NEW_ARTICLE: "CREATE_NEW_ARTICLE"
};
